export default {
    FILES: {
        SET_DIRECTORY: 'SET_DIRECTORY',
        CLEAR_DIRECTORY: 'CLEAR_DIRECTORY',
        FILE_STATUS_INIT: 'FILE_STATUS_INIT',
        FILE_STATUS_SUCCESS: 'FILE_STATUS_SUCCESS',
        FILE_STATUS_FAILURE: 'FILE_STATUS_FAILURE',
        SET_CT_SUMMARY: 'SET_CT_SUMMARY',
        CLEAR_CT_SUMMARY: 'SET_CT_SUMMARY',
        SET_RS_SUMMARY: 'SET_RS_SUMMARY',
        CLEAR_RS_SUMMARY: 'SET_RS_SUMMARY'
    },
    PATIENT: {
        SET_PATIENT_FIRST: 'SET_PATIENT_FIRST',
        CLEAR_PATIENT_FIRST: 'CLEAR_PATIENT_FIRST',
        SET_PATIENT_MIDDLE: 'SET_PATIENT_MIDDLE',
        CLEAR_PATIENT_MIDDLE: 'CLEAR_PATIENT_MIDDLE',
        SET_PATIENT_LAST: 'SET_PATIENT_LAST',
        CLEAR_PATIENT_LAST: 'CLEAR_PATIENT_LAST',
        SET_PATIENT_ID: 'SET_PATIENT_ID',
        CLEAR_PATIENT_ID: 'CLEAR_PATIENT_ID'
    },
    DOCTOR: {
        SET_DOCTOR_FIRST: 'SET_DOCTOR_FIRST',
        CLEAR_DOCTOR_FIRST: 'CLEAR_DOCTOR_FIRST',
        SET_DOCTOR_MIDDLE: 'SET_DOCTOR_MIDDLE',
        CLEAR_DOCTOR_MIDDLE: 'CLEAR_DOCTOR_MIDDLE',
        SET_DOCTOR_LAST: 'SET_DOCTOR_LAST',
        CLEAR_DOCTOR_LAST: 'CLEAR_DOCTORT_LAST',
        SET_DOCTOR_ID: 'SET_DOCTOR_ID',
        CLEAR_DOCTOR_ID: 'CLEAR_DOCTOR_ID'
    }
}