export default {
    DIRECTORY: {
        SET_DIRECTORY: 'SET_DIRECTORY',
        CLEAR_DIRECTORY: 'CLEAR_DIRECTORY',
        SET_SERIES: 'SET_SERIES',
        CLEAR_SERIES: 'CLEAR_SERIES'
    },
    PATIENT: {
        SET_PATIENT_FIRST: 'SET_PATIENT_FIRST',
        CLEAR_PATIENT_FIRST: 'CLEAR_PATIENT_FIRST',
        SET_PATIENT_MIDDLE: 'SET_PATIENT_MIDDLE',
        CLEAR_PATIENT_MIDDLE: 'CLEAR_PATIENT_MIDDLE',
        SET_PATIENT_LAST: 'SET_PATIENT_LAST',
        CLEAR_PATIENT_LAST: 'CLEAR_PATIENT_LAST',
        SET_PATIENT_ID: 'SET_PATIENT_ID',
        CLEAR_PATIENT_ID: 'CLEAR_PATIENT_ID'
    },
    DOCTOR: {
        SET_DOCTOR_FIRST: 'SET_DOCTOR_FIRST',
        CLEAR_DOCTOR_FIRST: 'CLEAR_DOCTOR_FIRST',
        SET_DOCTOR_MIDDLE: 'SET_DOCTOR_MIDDLE',
        CLEAR_DOCTOR_MIDDLE: 'CLEAR_DOCTOR_MIDDLE',
        SET_DOCTOR_LAST: 'SET_DOCTOR_LAST',
        CLEAR_DOCTOR_LAST: 'CLEAR_DOCTORT_LAST',
        SET_DOCTOR_ID: 'SET_DOCTOR_ID',
        CLEAR_DOCTOR_ID: 'CLEAR_DOCTOR_ID'
    }
}